version: '3.7'
services:
  gateway:
    image: ${REGISTRY}/todo-gateway:${IMAGE_TAG}
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/html:/var/www/html:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend-nginx
      - api-nginx

  frontend-nginx:
    image: ${REGISTRY}/todo-frontend:${IMAGE_TAG}
    restart: always

  api-nginx:
    image: ${REGISTRY}/todo-api:${IMAGE_TAG}
    restart: always
    depends_on:
      - api-php-fpm

  api-php-fpm:
    image: ${REGISTRY}/todo-api-php-fpm:${IMAGE_TAG}
    restart: always