version: '3.3'
services:
  gateway:
    build:
      context: gateway/docker
      dockerfile: dev/nginx.docker
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - frontend-nginx
      - api-nginx

  frontend-nginx:
    build:
      context: ./frontend/docker
      dockerfile: dev/nginx.docker
    volumes:
      - ./frontend:/var/www/frontend
    depends_on:
      - api-php-fpm
  frontend-nodejs:
    image: node:10.11-jessie
    volumes:
      - ./frontend:/var/www/frontend
    working_dir: /var/www/frontend
    tty: true

  api-nginx:
    build:
      context: ./api/docker
      dockerfile: dev/nginx.docker
    volumes:
      - ./api:/var/www/api
    depends_on:
      - api-php-fpm
  api-php-fpm:
    build:
      context: ./api/docker
      dockerfile: dev/php-fpm.docker
    environment:
      PHP_IDE_CONFIG: "serverName=API"
      MAILER_HOST: mailer
      MAILER_PORT: 1025
      MAILER_USER: app
      MAILER_PASSWORD: secret
      MAILER_ENCRYPTION: tcp
      MAILER_FROM: app@admin.test
      SENTRY_DSN: null
    volumes:
      - ./api:/var/www/api
      - ./storage:/var/www/storage
    depends_on:
      - api-postgres
  api-php-cli:
    build:
      context: ./api/docker
      dockerfile: dev/php-cli.docker
    environment:
      SENTRY_DSN: null
      MAILER_HOST: mailer
      MAILER_PORT: 1025
      MAILER_USER: app
      MAILER_PASSWORD: secret
      MAILER_ENCRYPTION: tcp
      MAILER_FROM: app@admin.test
    volumes:
      - ./api:/var/www/api
      - ./storage:/var/www/storage
    depends_on:
      - api-postgres
    working_dir: /var/www/api
    tty: true
  api-postgres:
    image: postgres:11.2-alpine
    volumes:
      - api-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "54321:5432"
  api-storage-nginx:
    build:
      context: ./storage/docker
      dockerfile: nginx.docker
    volumes:
      - ./storage:/var/www/storage
    ports:
      - "8082:80"

volumes:
  api-postgres:
  composer:
