// User
export const LOGIN = "login"
export const LOGOUT = "logout"
export const REFRESH = "refresh"
export const SIGN_UP = "signUp"
export const CONFIRM_SIGN_UP = "confirmSignUp"

// Todo
export const FETCH_SIDEBAR_MAIN_SCHEDULE_TASKS_COUNT = "FETCH_SIDEBAR_MAIN_SCHEDULE_TASKS_COUNT"
export const FETCH_SIDEBAR_DAILY_SCHEDULE_TASKS_COUNT = "FETCH_SIDEBAR_DAILY_SCHEDULE_TASKS_COUNT"
export const FETCH_SIDEBAR_CUSTOM_SCHEDULES_LIST = "FETCH_SIDEBAR_CUSTOM_SCHEDULES_LIST"
export const ADD_SIDEBAR_CUSTOM_SCHEDULE = "ADD_SIDEBAR_CUSTOM_SCHEDULE"
export const REMOVE_SIDEBAR_CUSTOM_SCHEDULE = "REMOVE_SIDEBAR_CUSTOM_SCHEDULE"
