// User
export const SET_USER = "SET_USER"
export const REMOVE_USER = "REMOVE_USER"
export const SET_AUTH_FORM_USERNAME = "SET_AUTH_FORM_USERNAME"
export const SET_AUTH_FORM_PASSWORD = "SET_AUTH_FORM_PASSWORD"
export const CLEAR_AUTH_FORM = "CLEAR_AUTH_FORM"
export const SET_AUTH_FORM_ERROR = "SET_AUTH_FORM_ERROR"
export const CLEAR_AUTH_FORM_ERROR = "CLEAR_AUTH_FORM_ERROR"
