todo:
	ansible-playbook -i servers.yml todo.yml

renew-certificates:
	ansible-playbook -i servers.yml renew-ssl.yml

login:
	ansible-playbook -i servers.yml docker-login.yml

authorize:
	ansible-playbook -i servers.yml auth.yml

upgrade:
	ansible-playbook -i servers.yml upgrade.yml