---
-   name: Provision Site
    hosts: all
    remote_user: root
    vars_files:
      - envs/certbot.yml
    tasks:
      -   import_tasks: tasks/docker.yml
      -   import_tasks: tasks/certbot.yml
      -   import_tasks: tasks/ssl.yml
    handlers:
      -   name: Start docker on boot
          systemd:
            name: docker
            state: started
            enabled: yes